//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the MSBuild WriteCodeFragment class.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: System.Reflection.AssemblyCompanyAttribute("FileDownloader")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("FileDownloader")]
[assembly: System.Reflection.AssemblyTitleAttribute("FileDownloader")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: InternalsVisibleTo("FileDownloader.Tests")]
